# Generated by Django 6.0.6 on 2026-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='A short name for this rule', max_length=200)),
                ('field_name', models.CharField(help_text='Which field to check, e.g. salary, age, credit_score', max_length=100)),
                ('operator', models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater Than or Equal'), ('<=', 'Less Than or Equal'), ('==', 'Equal To'), ('!=', 'Not Equal To')], help_text='Comparison operator', max_length=10)),
                ('value', models.CharField(help_text='The value to compare against', max_length=200)),
                ('category', models.CharField(choices=[('mandatory', 'Mandatory'), ('scoring', 'Scoring'), ('warning', 'Warning'), ('informational', 'Informational')], default='scoring', max_length=20)),
                ('priority', models.IntegerField(default=10, help_text='Lower number runs first')),
                ('weight', models.IntegerField(default=0, help_text='Score added when this rule passes (used for scoring rules)')),
                ('action', models.CharField(choices=[('reject', 'Reject'), ('add_score', 'Add Score'), ('warning', 'Warning'), ('info', 'Info'), ('continue', 'Continue')], default='add_score', max_length=20)),
                ('explanation_pass', models.TextField(blank=True, default='', help_text='Message shown when the rule passes')),
                ('explanation_fail', models.TextField(blank=True, default='', help_text='Message shown when the rule fails')),
                ('is_active', models.BooleanField(default=True, help_text='Only active rules are used during evaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='DecisionThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Threshold', max_length=100)),
                ('min_score_approve', models.IntegerField(default=80, help_text='Score >= this means Approved')),
                ('min_score_review', models.IntegerField(default=60, help_text='Score >= this but < approve means Manual Review')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default='Anonymous', max_length=200)),
                ('application_data', models.TextField(help_text='JSON string of the submitted data')),
                ('decision', models.CharField(max_length=20)),
                ('final_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='unknown', max_length=20)),
                ('rules_passed', models.TextField(default='[]', help_text='JSON list of passed rule names')),
                ('rules_failed', models.TextField(default='[]', help_text='JSON list of failed rule names')),
                ('warnings', models.TextField(default='[]', help_text='JSON list of warning messages')),
                ('info_messages', models.TextField(default='[]', help_text='JSON list of info messages')),
                ('full_explanation', models.TextField(default='', help_text='Complete human-readable explanation')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
