# Generated by Django 6.0.6 on 2026-06-29 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrule',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Notes from admin when approving or rejecting'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created or submitted this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='parent_rule',
            field=models.ForeignKey(blank=True, help_text='If this is a draft edit, points to the original rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_versions', to='Rules.businessrule'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='active', help_text='Current status of the rule in the approval workflow', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationlog',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, help_text='The employee who ran this evaluation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
    ]
